
$rosewater = rgb(dc8a78)
$rosewaterAlpha = "##3dc8a78"

$flamingo = rgb(dd7878)
$flamingoAlpha = "##3dd7878"

$pink = rgb(ea76cb)
$pinkAlpha = "##3ea76cb"

$mauve = rgb(8839ef)
$mauveAlpha = "##38839ef"

$red = rgb(d20f39)
$redAlpha = "##3d20f39"

$maroon = rgb(e64553)
$maroonAlpha = "##3e64553"

$peach = rgb(fe640b)
$peachAlpha = "##3fe640b"

$yellow = rgb(df8e1d)
$yellowAlpha = "##3df8e1d"

$green = rgb(40a02b)
$greenAlpha = "##340a02b"

$teal = rgb(179299)
$tealAlpha = "##3179299"

$sky = rgb(04a5e5)
$skyAlpha = "##304a5e5"

$sapphire = rgb(209fb5)
$sapphireAlpha = "##3209fb5"

$blue = rgb(1e66f5)
$blueAlpha = "##31e66f5"

$lavender = rgb(7287fd)
$lavenderAlpha = "##37287fd"

$text = rgb(4c4f69)
$textAlpha = "##34c4f69"

$subtext1 = rgb(5c5f77)
$subtext1Alpha = "##35c5f77"

$subtext0 = rgb(6c6f85)
$subtext0Alpha = "##36c6f85"

$overlay2 = rgb(7c7f93)
$overlay2Alpha = "##37c7f93"

$overlay1 = rgb(8c8fa1)
$overlay1Alpha = "##38c8fa1"

$overlay0 = rgb(9ca0b0)
$overlay0Alpha = "##39ca0b0"

$surface2 = rgb(acb0be)
$surface2Alpha = "##3acb0be"

$surface1 = rgb(bcc0cc)
$surface1Alpha = "##3bcc0cc"

$surface0 = rgb(ccd0da)
$surface0Alpha = "##3ccd0da"

$base = rgb(eff1f5)
$baseAlpha = "##3eff1f5"

$mantle = rgb(e6e9ef)
$mantleAlpha = "##3e6e9ef"

$crust = rgb(dce0e8)
$crustAlpha = "##3dce0e8"
